[package]
name = "twitch-discord-moderation"
version = "0.2.0"
authors = ["Emil Gardström <emil.gardstrom@gmail.com>"]
edition = "2018"
license = "MIT OR APACHE-2.0"
default-run = "twitch-discord-moderation"
readme = "README.md"
description = "Bot to send twitch moderator actions to a discord webhook"
publish = false
repository = "https://github.com/Emilgardis/twitch_discord_moderation"
build = "build.rs"

[dependencies]
tokio = { version = "1.5.0", features = ["full"] }
tracing = "0.1.25"
tracing-subscriber = "0.2.17"
tracing-futures = "0.2.5"
tracing-log = "0.1.2"
anyhow = "1.0.40"
chrono = "0.4.19"
ansi_term = "0.12.1"
dotenv = "0.15.0"
twitch_api2 = { version = "0.5.0-alpha.5", features = ["reqwest_client", "helix", "pubsub"] }
twitch_oauth2 = { version = "0.5.0-alpha.5", features = ["reqwest_client"] }
async-tungstenite = { version = "0.13.1", features = ["tokio-native-tls"] }
reqwest = { version = "0.11.3", features = ["json"] }
url = "2.2.1"
futures = "0.3.14"
discord_webhook = { git = "https://github.com/thoo0224/webhook-rs", rev = "dc217e1fe", package = "webhook" }
humantime = "2.1.0"
serde = "1.0.125"
serde_json = "1.0.64"
fastrand = "1.4.0"
clap = {git = "https://github.com/clap-rs/clap", rev = "d253c34" }

[build-dependencies]
vergen = "5.1.1"
anyhow = "1.0.40"
git-version = "0.3.4"

[target.'cfg(not(any(windows, unix, macos)))'.dependencies]
reqwest = { version = "0.11.3", features = ["rustls-tls", "json"] }


[patch.crates-io]
#twitch_api2 = { path = "../twitch_api2" }
#twitch_oauth2 = { path = "../twitch_api2/twitch_oauth2" }
twitch_api2 = { git = "https://github.com/Emilgardis/twitch_api2.git", rev = "3c9886f" }
twitch_oauth2 = { git = "https://github.com/Emilgardis/twitch_api2.git", rev = "3c9886f" }
#tungstenite = {path = "../tungstenite-rs"}