[package]
name = "twitch-discord-moderation"
version = "0.3.0"
authors = ["Emil Gardström <emil.gardstrom@gmail.com>"]
edition = "2021"
license = "MIT OR APACHE-2.0"
default-run = "twitch-discord-moderation"
readme = "README.md"
description = "Bot to send twitch moderator actions to a discord webhook"
publish = false
repository = "https://github.com/Emilgardis/twitch_discord_moderation"
build = "build.rs"

[dependencies]
tokio = { version = "1.15.0", features = ["full"] }
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.15", features = [
    "env-filter",
    "std",
    "fmt",
] }
tracing-futures = "0.2.5"
tracing-log = "0.1.2"
anyhow = "1.0.52"
chrono = "0.4.19"
ansi_term = "0.12.1"
dotenv = "0.15.0"
twitch_api = { version = "0.6.1", features = ["reqwest", "helix", "pubsub"] }
async-tungstenite = { version = "0.17.2", features = ["tokio-native-tls"] }
reqwest = { version = "0.11.9", features = ["json"] }
url = "2.2.2"
futures = "0.3.19"
discord_webhook = { git = "https://github.com/thoo0224/webhook-rs", rev = "dc217e1fe", package = "webhook" }
humantime = "2.1.0"
serde = "1.0.133"
serde_json = "1.0.75"
fastrand = "1.6.0"
clap = { version = "3.0", features = ["derive", "env"] }
once_cell = "1.9.0"

[workspace]
members = ["xtask"]

[build-dependencies]
built = { version = "0.5.1", features = ["chrono", "git2"] }

[dev-dependencies]
pretty_assertions = "1.3.0"

[target.'cfg(all(not(any(target_os = "windows", target_os = "macos", target_os = "ios")), target_env = "musl"))'.dependencies]
#openssl = { version = "0.10.33", features = ["vendored"] }

[patch.crates-io]
#twitch_api = { path = "../twitch_api" }
#twitch_oauth2 = { path = "../twitch_api/twitch_oauth2" }
twitch_api = { git = "https://github.com/twitch-rs/twitch_api.git" }
twitch_types = { git = "https://github.com/twitch-rs/twitch_api.git" }
#tungstenite = {path = "../tungstenite-rs"}
