[workspace]
members = [
    "server",
    "xtask",
]

[patch.crates-io]
#twitch_api2 = { path = "../twitch_api2" }
#twitch_oauth2 = { path = "../twitch_api2/twitch_oauth2" }
twitch_api2 = { git = "https://github.com/Emilgardis/twitch_api2.git", branch = "pubsub" }
twitch_oauth2 = { git = "https://github.com/Emilgardis/twitch_api2.git", branch = "pubsub" }
