#!/bin/bash
export DOCKER_CLI_EXPERIMENTAL=enabled
export DOCKER_BUILDKIT=1
docker buildx create \
	--name builder \
	--driver docker-container \
	--platform linux/amd64,linux/arm64,linux/arm/v7 \
	--use
docker buildx inspect --bootstrap