name: docker
on:
  push:
    branches: ['main']
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - "docker-bake.hcl"
      - "Dockerfile"
jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@v1.3.0
        with:
          push: true
          files: docker-bake.hcl
      # disabled due to needing a password
      # - name: Docker Hub Description
      #   uses: peter-evans/dockerhub-description@v2.4.2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
      #     short-description: ${{ github.event.repository.description }}
      #     repository: emilgardis/twitch-discord-moderation